augment: true
batch: 16
box: 7.5
cls: 0.5
copy_paste: 0.1
cos_lr: true
data: /content/drive/MyDrive/KTP_YOLO_Project/ktp-object-detection-1/data.yaml
degrees: 10.0
device: '0'
dfl: 1.5
dropout: 0.2
epochs: 150
erasing: 0.4
fliplr: 0.5
flipud: 0.1
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
imgsz: 640
iou: 0.7
lr0: 0.001
lrf: 0.01
mixup: 0.2
momentum: 0.937
mosaic: 1.0
name: ktp_yolov8m_prod
optimizer: AdamW
patience: 30
perspective: 0.001
pretrained: true
project: /content/drive/MyDrive/KTP_YOLO_Project
rect: false
resume: false
scale: 0.5
shear: 2.0
single_cls: false
translate: 0.1
warmup_bias_lr: 0.1
warmup_epochs: 3
warmup_momentum: 0.8
weight_decay: 0.0005
workers: 8
